Questionnaire/Questionnaire.WEB/Controllers/AnswerController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Infrastructure.Exceptions;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class AnswerController : Controller
    {
        private const int _itemsPerPage = 10;
        private IAnswerService AnswerService;

        public AnswerController(IAnswerService answerService)
        {
            AnswerService = answerService;
        }

        [Authorize(Roles = "admin, manager")]
        public ActionResult AjaxAnswerList(int? page)
        {
            IEnumerable<AnswerDTO> answerDTOs = AnswerService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<AnswerVM> answerVMs = Mapper.Map<IEnumerable<AnswerVM>>(answerDTOs);

            return PartialView(answerVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Answer
        [Authorize(Roles = "admin, manager")]
        public ActionResult Index(int? page)
        {

            IEnumerable<AnswerDTO> answerDTOs = AnswerService
               .GetListOrderedByName()
               .ToList();
            IEnumerable<AnswerVM> answerVMs = Mapper.Map<IEnumerable<AnswerVM>>(answerDTOs);

            return View(answerVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Answer/Details/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Details(int? id)
        {
            try
            {
                AnswerDTO answerDTO = AnswerService.Get(id);
                AnswerVM answerVMs = Mapper.Map<AnswerVM>(answerDTO);

                return View(answerVMs);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        // GET: Answer/Create
        [Authorize(Roles = "admin, manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Answer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, manager")]
        public ActionResult Create([Bind(Include = "Name")] AnswerVM answerVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AnswerDTO answerDTO = Mapper.Map<AnswerDTO>(answerVM);
                    AnswerService.Add(answerDTO);
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new
                {
                    hasError = true,
                    data = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Answer/Edit/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Edit(int? id)
        {
            try
            {
                AnswerDTO answerDTO = AnswerService.Get(id);
                AnswerVM answerVM = Mapper.Map<AnswerVM>(answerDTO);
                return View(answerVM);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        // POST: Answer/Edit/5
        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] AnswerVM answerVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AnswerDTO answerDTO = Mapper.Map<AnswerDTO>(answerVM);
                    AnswerService.Update(answerDTO);
                    return RedirectToAction("Index");
                }
                return View(answerVM);
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new
                {
                    hasError = true,
                    data = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Answer/Delete/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                AnswerService.Delete(id);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
            catch (HasRelationsException)
            {
                return Content("Удаление невозможно.");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FindAnswers(string value, string type)
        {
            value = value.Trim().ToLower();

            List<AnswerDTO> answerDTOs = AnswerService
                .GetAnswersBy(type, value)
                .ToList();

            List<AnswerVM> answerVMs = Mapper.Map<IEnumerable<AnswerVM>>(answerDTOs).ToList();

            return PartialView(answerVMs);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Questionnaire/Questionnaire.WEB/Controllers/InterviewerController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Infrastructure.Exceptions;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class InterviewerController : Controller
    {
        private const int _itemsPerPage = 10;
        private IInterviewerService InterviewerService;

        public InterviewerController(IInterviewerService interviewerService)
        {
            InterviewerService = interviewerService;
        }

        [Authorize(Roles = "admin, manager, user")]
        public ActionResult AjaxInterviewerList(int? page)
        {
            IEnumerable<InterviewerDTO> interviewerDTOs = InterviewerService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<InterviewerVM> interviewerVMs = Mapper.Map<IEnumerable<InterviewerVM>>(interviewerDTOs);

            return PartialView(interviewerVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Interviewer
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Index(int? page)
        {

            IEnumerable<InterviewerDTO> interviewerDTOs = InterviewerService
               .GetListOrderedByName()
               .ToList();
            IEnumerable<InterviewerVM> interviewerVMs = Mapper.Map<IEnumerable<InterviewerVM>>(interviewerDTOs);

            return View(interviewerVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Interviewer/Details/5
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Details(int? id)
        {
            try
            {
                InterviewerDTO interviewerDTO = InterviewerService.Get(id);
                InterviewerVM interviewerVMs = Mapper.Map<InterviewerVM>(interviewerDTO);

                return View(interviewerVMs);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        // GET: Interviewer/Create
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Interviewer/Create
        [HttpPost]
        [Authorize(Roles = "admin, manager, user")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, Phone")] InterviewerVM interviewerVM)
        {
            if (ModelState.IsValid)
            {
                InterviewerDTO interviewerDTO = Mapper.Map<InterviewerDTO>(interviewerVM);
                InterviewerService.Add(interviewerDTO);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Interviewer/Edit/5
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Edit(int? id)
        {
            try
            {
                InterviewerDTO interviewerDTO = InterviewerService.Get(id);
                InterviewerVM interviewerVM = Mapper.Map<InterviewerVM>(interviewerDTO);
                return View(interviewerVM);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        // POST: Interviewer/Edit/5
        [HttpPost]
        [Authorize(Roles = "admin, manager, user")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Phone")] InterviewerVM interviewerVM)
        {
            if (ModelState.IsValid)
            {
                InterviewerDTO interviewerDTO = Mapper.Map<InterviewerDTO>(interviewerVM);
                InterviewerService.Update(interviewerDTO);
                return RedirectToAction("Index");
            }
            return View(interviewerVM);
        }

        // GET: Interviewer/Delete/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                InterviewerService.Delete(id);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
            catch (HasRelationsException)
            {
                return Content("Удаление невозможно.");
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Questionnaire/Questionnaire.WEB/Controllers/QuestionController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Infrastructure.Exceptions;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class QuestionController : Controller
    {
        private const int _itemsPerPage = 10;
        private IQuestionTypeService QuestionTypeService;
        private IQuestionService QuestionService;

        public QuestionController(IQuestionTypeService questionTypeService,IQuestionService questionService)
        {
            QuestionTypeService = questionTypeService;
            QuestionService = questionService;
        }

        [Authorize(Roles = "admin, manager")]
        public ActionResult AjaxQuestionTypeList(int? page)
        {
            IEnumerable<QuestionDTO> questionDTOs = QuestionService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<QuestionVM> questionVMs = Mapper.Map<IEnumerable<QuestionVM>>(questionDTOs);

            return PartialView(questionVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }
        // GET: Question
        [Authorize(Roles = "admin, manager")]
        public ActionResult Index(int? page)
        {
            IEnumerable<QuestionDTO> questionDTOs = QuestionService
               .GetListOrderedByName()
               .ToList();
            IEnumerable<QuestionVM> questionVMs = Mapper.Map<IEnumerable<QuestionVM>>(questionDTOs);

            return View(questionVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Question/Details/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Details(int? id)
        {
            try
            {
                QuestionDTO questionDTO = QuestionService.Get(id);
                QuestionVM questionVM = Mapper.Map<QuestionVM>(questionDTO);

                return View(questionVM);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        [Authorize(Roles = "admin, manager")]
        public ActionResult Create()
        {
            ViewBag.QuestionTypeId = GetQuestionTypeIdSelectList();

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QuestionTypeId,Name,MultipleAnswer")] QuestionVM questionVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    QuestionDTO questionDTO = Mapper.Map<QuestionDTO>(questionVM);
                    //int questionId = QuestionService.AddAndGetId(questionDTO);
                    QuestionService.Add(questionDTO);
                    return RedirectToAction("Index");
                }

                ViewBag.QuestionTypeId = GetQuestionTypeIdSelectList(questionVM.QuestionTypeId);

                return View(questionVM);
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new
                {
                    hasError = true,
                    data = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Question/Edit/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Edit(int? id)
        {
            try
            {
                QuestionDTO questionDTO = QuestionService.Get(id);
                QuestionVM questionVM = Mapper.Map<QuestionVM>(questionDTO);

                ViewBag.QuestionTypeId = GetQuestionTypeIdSelectList(questionVM.QuestionTypeId);

                return View(questionVM);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,QuestionTypeId,Name,MultipleAnswer")] QuestionVM questionVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    QuestionDTO questionDTO = Mapper.Map<QuestionDTO>(questionVM);
                    QuestionService.Update(questionDTO);
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError(null, "Что-то пошло не так. Не удалось сохранить изменения.");

                ViewBag.QuestionTypeId = GetQuestionTypeIdSelectList(questionVM.QuestionTypeId);

                return View(questionVM);
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new
                {
                    hasError = true,
                    data = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public SelectList GetQuestionTypeIdSelectList(short? selectedValue = null)
        {
            return new SelectList(QuestionTypeService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        [Authorize(Roles = "admin, manager")]
        public ActionResult Answers(int? questionId)
        {
            try
            {
                IEnumerable<AnswerDTO> answerDTOs = QuestionService.GetAnswers(questionId).ToList();
                IEnumerable<AnswerVM> answerVMs = Mapper.Map<IEnumerable<AnswerVM>>(answerDTOs);

                ViewBag.QuestionId = questionId;

                return View(answerVMs);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // GET: Question/Delete/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                QuestionService.Delete(id);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
            catch (HasRelationsException)
            {
                return Content("Удаление невозможно.");
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Questionnaire/Questionnaire.WEB/Views/Search/Answers.cshtml
@model IEnumerable<Questionnaire.WEB.Models.Entities.AnswerVM>
<table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm" id="listTable">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr id="@item.Id">
                <td>@item.Name</td>

                <td>
                    @if (User.IsInRole("admin"))
                    {
                        <div class="btn-group float-right" role="group">
                            <a class="btn btn-info" name="editButton" id="editButton" href="@Url.Action("Edit", "Answer", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                            <a class="btn btn-warning" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "Answer", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                            <a class="btn btn-danger delete-prompt" name="deleteButton" id="@item.Id"><i class="fa fa-trash" aria-hidden="true" title="Удалить" data-toggle="tooltip" data-placement="top"></i> Удалить</a>
                        </div>
                    }
                    else if (User.IsInRole("manager"))
                    {
                        <div class="btn-group float-right" role="group">
                            <a class="btn btn-info" name="editButton" id="editButton" href="@Url.Action("Edit", "Answer", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                            <a class="btn btn-warning" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "Answer", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                        </div>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<button class="btn btn-default" onclick="toPrevMain()">Вернуться к списку</button>

<!-- Bootstrap modal popup -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Удаление</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="success-message"> Вы действительно хотите удалить запись? </p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger delete-confirm">Да</button>
                <button class="btn btn-default delete-cancel" data-dismiss="modal">Нет</button>
            </div>
        </div>
    </div>
</div>

<script>
    modalRemovalWindow('/Answer/Delete');
</script>

Questionnaire/Questionnaire.WEB/Views/Search/Interviewers.cshtml
@model IEnumerable<Questionnaire.WEB.Models.Entities.InterviewerVM>
<table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm" id="listTable">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Phone)</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr id="@item.Id">
                <td>@item.Name</td>
                <td>@item.Phone</td>

                <td>
                    @if (User.IsInRole("admin"))
                    {
                        <div class="btn-group float-right" role="group">
                            <a class="btn btn-info" name="editButton" id="editButton" href="@Url.Action("Edit", "Interviewer", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                            <a class="btn btn-warning" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "Interviewer", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                            <a class="btn btn-danger delete-prompt" name="deleteButton" id="@item.Id"><i class="fa fa-trash" aria-hidden="true" title="Удалить" data-toggle="tooltip" data-placement="top"></i> Удалить</a>
                        </div>
                    }
                    else if (User.IsInRole("manager") || User.IsInRole("user"))
                    {
                        <div class="btn-group float-right" role="group">
                            <a class="btn btn-info" name="editButton" id="editButton" href="@Url.Action("Edit", "Interviewer", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                            <a class="btn btn-warning" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "Interviewer", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                        </div>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<button class="btn btn-default" onclick="toPrevMain()">Вернуться к списку</button>

<!-- Bootstrap modal popup -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Удаление</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="success-message"> Вы действительно хотите удалить запись? </p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger delete-confirm">Да</button>
                <button class="btn btn-default delete-cancel" data-dismiss="modal">Нет</button>
            </div>
        </div>
    </div>
</div>

<script>
    modalRemovalWindow('/Interviewer/Delete');
</script>

Questionnaire/Questionnaire.WEB/Views/Search/NotFound.cshtml
<h4 style="text-align:center;"><u>Нет результатов</u></h4><br />
<button class="btn btn-default" onclick="toPrevMain()">Вернуться к списку</button>

Questionnaire/Questionnaire.WEB/Views/Search/Questions.cshtml
@model IEnumerable<Questionnaire.WEB.Models.Entities.QuestionVM>
<table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm" id="listTable">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.QuestionTypeId)</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.MultipleAnswer)</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr id="@item.Id">
                <td>@item.QuestionType.Name</td>
                <td>@item.Name</td>
                <td>@Html.DisplayFor(modelItem => item.MultipleAnswer) </td>

                <td>
                    @if (User.IsInRole("admin"))
                    {
                        <div class="btn-group float-right" role="group">
                            <a class="btn btn-success btn-sm" name="editButton" id="editButton" href="@Url.Action("Edit", "Question", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                            <a class="btn btn-warning btn-sm" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "Question", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                            <a class="btn btn-info btn-sm" name="detailsButton" id="detailsButton" href="@Url.Action("Answers", "Question", new { questionId = item.Id })"><i class="fa fa-list-alt" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Список ответов</a>
                            <a class="btn btn-danger delete-prompt btn-sm" name="deleteButton" id="@item.Id"><i class="fa fa-trash" aria-hidden="true" title="Удалить" data-toggle="tooltip" data-placement="top"></i> Удалить</a>
                        </div>
                    }
                    else if (User.IsInRole("manager"))
                    {
                        <div class="btn-group float-right" role="group">
                            <a class="btn btn-success btn-sm" name="editButton" id="editButton" href="@Url.Action("Edit", "Question", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                            <a class="btn btn-warning btn-sm" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "Question", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                            <a class="btn btn-info btn-sm" name="detailsButton" id="detailsButton" href="@Url.Action("Answers", "Question", new { questionId = item.Id })"><i class="fa fa-list-alt" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Список ответов</a>
                        </div>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<button class="btn btn-default" onclick="toPrevMain()">Вернуться к списку</button>

<!-- Bootstrap modal popup -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Удаление</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="success-message"> Вы действительно хотите удалить запись? </p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger delete-confirm">Да</button>
                <button class="btn btn-default delete-cancel" data-dismiss="modal">Нет</button>
            </div>
        </div>
    </div>
</div>

<script>
    modalRemovalWindow('/Question/Delete');
</script>