Questionnaire/Questionnaire.WEB/Controllers/SearchController.cs
using AutoMapper;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class SearchController : Controller
    {
        ISearchService SearchService;
        public SearchController(ISearchService searchService)
        {
            SearchService = searchService;
        }

        [Authorize(Roles = "admin, manager, user")]
        public ActionResult AdminSearch(string title, string type)
        {
            ModelAndViewDTO result = SearchService.GetFilteredModelAndView(title, type);

            if (result.Model.Count() > 0)
            {
                string modelType = result.Model.First().GetType().ToString().Split('.').Last();
                switch (modelType)
                {
                    case "QuestionTypeDTO":
                        result.Model = Mapper.Map<IEnumerable<QuestionTypeVM>>(result.Model);
                        break;
                    case "QuestionDTO":
                        result.Model = Mapper.Map<IEnumerable<QuestionVM>>(result.Model);
                        break;
                    case "AnswerDTO":
                        result.Model = Mapper.Map<IEnumerable<AnswerVM>>(result.Model);
                        break;
                    //case "ComponentTypeDTO":
                    //    result.Model = Mapper.Map<IEnumerable<ComponentTypeVM>>(result.Model);
                    //    break;
                    case "SurveyGeographyDTO":
                        result.Model = Mapper.Map<IEnumerable<SurveyGeographyVM>>(result.Model);
                        break;
                    case "HousingTypeDTO":
                        result.Model = Mapper.Map<IEnumerable<HousingTypeVM>>(result.Model);
                        break;
                    case "DistrictDTO":
                        result.Model = Mapper.Map<IEnumerable<DistrictVM>>(result.Model);
                        break;
                    case "InterviewerDTO":
                        result.Model = Mapper.Map<IEnumerable<InterviewerVM>>(result.Model);
                        break;
                    case "FamilyDTO":
                        result.Model = Mapper.Map<IEnumerable<FamilyVM>>(result.Model);
                        break;
                    case "FormDTO":
                        result.Model = Mapper.Map<IEnumerable<FormVM>>(result.Model);
                        break;
                }
            }
            else
                result.View = "NotFound";

            return PartialView(result.View, result.Model);
        }

        public ActionResult NotFoundResult()
        {
            return PartialView("~/Views/Error/NotFoundError.cshtml");
        }
    }
}

Questionnaire/Questionnaire.WEB/Controllers/SurveyGeographyController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Infrastructure.Exceptions;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class SurveyGeographyController : Controller
    {

        private const int _itemsPerPage = 10;
        private ISurveyGeographyService SurveyGeographyService;

        public SurveyGeographyController(ISurveyGeographyService surveyGeographyService)
        {
            SurveyGeographyService = surveyGeographyService;
        }

        [Authorize(Roles = "admin, manager")]
        public ActionResult AjaxSurveyGeographyList(int? page)
        {
            IEnumerable<SurveyGeographyDTO> surveyGeographyDTOs = SurveyGeographyService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<SurveyGeographyVM> surveyGeographyVMs = Mapper.Map<IEnumerable<SurveyGeographyVM>>(surveyGeographyDTOs);

            return PartialView(surveyGeographyVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: SurveyGeography
        [Authorize(Roles = "admin, manager")]
        public ActionResult Index(int? page)
        {

            IEnumerable<SurveyGeographyDTO> surveyGeographyDTOs = SurveyGeographyService
               .GetListOrderedByName()
               .ToList();
            IEnumerable<SurveyGeographyVM> surveyGeographyVMs = Mapper.Map<IEnumerable<SurveyGeographyVM>>(surveyGeographyDTOs);

            return View(surveyGeographyVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: SurveyGeography/Details/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Details(int? id)
        {
            try
            {
                SurveyGeographyDTO surveyGeographyDTO = SurveyGeographyService.Get(id);
                SurveyGeographyVM surveyGeographyVMs = Mapper.Map<SurveyGeographyVM>(surveyGeographyDTO);

                return View(surveyGeographyVMs);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        // GET: SurveyGeography/Create
        [Authorize(Roles = "admin, manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: SurveyGeography/Create
        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name")] SurveyGeographyVM surveyGeographyVM)
        {
            if (ModelState.IsValid)
            {
                SurveyGeographyDTO surveyGeographyDTO = Mapper.Map<SurveyGeographyDTO>(surveyGeographyVM);
                SurveyGeographyService.Add(surveyGeographyDTO);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: SurveyGeography/Edit/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Edit(int? id)
        {
            try
            {
                SurveyGeographyDTO surveyGeographyDTO = SurveyGeographyService.Get(id);
                SurveyGeographyVM surveyGeographyVM = Mapper.Map<SurveyGeographyVM>(surveyGeographyDTO);
                return View(surveyGeographyVM);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        // POST: SurveyGeography/Edit/5
        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] SurveyGeographyVM surveyGeographyVM)
        {
            if (ModelState.IsValid)
            {
                SurveyGeographyDTO surveyGeographyDTO = Mapper.Map<SurveyGeographyDTO>(surveyGeographyVM);
                SurveyGeographyService.Update(surveyGeographyDTO);
                return RedirectToAction("Index");
            }
            return View(surveyGeographyVM);
        }

        // GET: SurveyGeography/Delete/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                SurveyGeographyService.Delete(id);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
            catch (HasRelationsException)
            {
                return Content("Удаление невозможно.");
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Questionnaire/Questionnaire.WEB/Views/SurveyGeography/AjaxSurveyGeographyList.cshtml
@model PagedList.IPagedList<Questionnaire.WEB.Models.Entities.SurveyGeographyVM>
@using PagedList;
@using PagedList.Mvc;

<table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm" id="listTable">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.First().Name)</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr id="@item.Id">
                <td>@Html.DisplayFor(modelItem => item.Name)</td>

                <td>
                    @if (User.IsInRole("admin"))
                    {
                        <div class="btn-group float-right" role="group">
                            <a class="btn btn-info" name="editButton" id="editButton" href="@Url.Action("Edit", "SurveyGeography", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                            <a class="btn btn-warning" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "SurveyGeography", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                            <a class="btn btn-danger delete-prompt" name="deleteButton" id="@item.Id"><i class="fa fa-trash" aria-hidden="true" title="Удалить" data-toggle="tooltip" data-placement="top"></i> Удалить</a>
                        </div>
                    }
                    else if (User.IsInRole("manager"))
                    {
                        <div class="btn-group float-right" role="group">
                            <a class="btn btn-info" name="editButton" id="editButton" href="@Url.Action("Edit", "SurveyGeography", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                            <a class="btn btn-warning" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "SurveyGeography", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                        </div>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager(Model, page => Url.Action("AjaxSurveyGeographyList", new { page }),
 PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "result" }))
    Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount

    <!-- Bootstrap modal popup -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">Удаление</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class="success-message"> Вы действительно хотите удалить запись? </p>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger delete-confirm">Да</button>
                    <button class="btn btn-default delete-cancel" data-dismiss="modal">Нет</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        modalRemovalWindow('/SurveyGeography/Delete');
    </script>

Questionnaire/Questionnaire.WEB/Views/SurveyGeography/Create.cshtml
@model Questionnaire.WEB.Models.Entities.SurveyGeographyVM

@{
    ViewBag.Title = "Добавление мест обследования";
}

<div class="block">
    <h2 class="block-title">Добавление мест обследования</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autofocus = "autofocus", @autocomplete = "off" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <div class="btn-group" role="group">
                    <button type="submit" class="btn btn-success"><i class="fa fa-save" aria-hidden="true" title="Сохранить" data-toggle="tooltip" data-placement="top"></i> Сохранить</button>
                    <a href="@Url.Action("Index", "SurveyGeography")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>
                </div>
            </div>
        </div>
    }
</div>

Questionnaire/Questionnaire.WEB/Views/SurveyGeography/Details.cshtml
@model Questionnaire.WEB.Models.Entities.SurveyGeographyVM

@{
    ViewBag.Title = "Подробная информация";
}

<div class="block">
    <h2 clss="block-title">Подробная информация</h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
    </div>

    <div class="form-group">
        <div class="btn-group" role="group">
            <a href="@Url.Action("Edit", "SurveyGeography", new { id = Model.Id})" class="btn btn-success"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
            <a href="@Url.Action("Index", "SurveyGeography")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>
        </div>
    </div>
</div>

Questionnaire/Questionnaire.WEB/Views/SurveyGeography/Edit.cshtml
@model Questionnaire.WEB.Models.Entities.SurveyGeographyVM

@{
    ViewBag.Title = "Редактирование";
}

<div class="block">
    <h2 class="block-title">Редактирование</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @autocomlete = "off" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <div class="btn-group" role="group">
                    <button type="submit" class="btn btn-success"><i class="fa fa-save" aria-hidden="true" title="Сохранить" data-toggle="tooltip" data-placement="top"></i> Сохранить</button>
                    <a href="@Url.Action("Index", "SurveyGeography")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>
                </div>
            </div>
        </div>
    }
</div>

Questionnaire/Questionnaire.WEB/Views/SurveyGeography/Index.cshtml
@model PagedList.IPagedList<Questionnaire.WEB.Models.Entities.SurveyGeographyVM>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "География обследования";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block">
    <h2 class="block-title">География обследования</h2>

    @Html.AntiForgeryToken()

    <p>
        <a type="button" class="btn btn-primary app-btn app-btn-main" href="@Url.Action("Create", "SurveyGeography")"> <i class="fa fa-plus"></i> Добавить новую запись</a>
    </p>

    @using (Ajax.BeginForm("AdminSearch", "Search", null,
    new AjaxOptions
    {
        UpdateTargetId = "results",
        LoadingElementId = "loading",
        OnSuccess = "hideAccordion()"
    },
    new { @class = "ajax-form", @id = "ajax-form" }))
    {
        <input type="hidden" name="type" value="surveyGeography" />

        <div class="input-group mb-3">
            <input type="text" id="xyz-search-input" name="title" class="form-control" placeholder="Введите наименование места обследования" autocomplete="off" required>
            <div class="input-group-append">
                <button type="submit" class="btn btn-default"><span class="fa fa-search"></span> Искать <span id="loading" class="loading" style="display:none"><svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.0" width="16px" height="16px" viewBox="0 0 128 128" xml:space="preserve"><g transform="rotate(352.65 64.0001 64.0001)"><linearGradient id="linear-gradient"><stop offset="0%" stop-color="#ffffff"></stop><stop offset="100%" stop-color="#454445"></stop></linearGradient><path d="M63.85 0A63.85 63.85 0 1 1 0 63.85 63.85 63.85 0 0 1 63.85 0zm.65 19.5a44 44 0 1 1-44 44 44 44 0 0 1 44-44z" fill="url(#linear-gradient)" fill-rule="evenodd"></path><animateTransform attributeName="transform" type="rotate" from="0 64 64" to="360 64 64" dur="1080ms" repeatCount="indefinite"></animateTransform></g></svg></span></button>
            </div>
        </div>
    }

    <div id="results" class="content"></div>

    <div class="content" id="accordion">
        <table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm" id="listTable">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.First().Name)</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id">
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>

                        <td>
                            @if (User.IsInRole("admin"))
                            {
                                <div class="btn-group float-right" role="group">
                                    <a class="btn btn-info" name="editButton" id="editButton" href="@Url.Action("Edit", "SurveyGeography", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                                    <a class="btn btn-warning" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "SurveyGeography", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                                    <a class="btn btn-danger delete-prompt" name="deleteButton" id="@item.Id"><i class="fa fa-trash" aria-hidden="true" title="Удалить" data-toggle="tooltip" data-placement="top"></i> Удалить</a>
                                </div>
                            }
                            else if (User.IsInRole("manager"))
                            {
                                <div class="btn-group float-right" role="group">
                                    <a class="btn btn-info" name="editButton" id="editButton" href="@Url.Action("Edit", "SurveyGeography", new { id = item.Id })"><i class="fa fa-pencil" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                                    <a class="btn btn-warning" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "SurveyGeography", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                                </div>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div id="result"> </div>

        <div id="paginationToDelete">
            @Html.PagedListPager(Model, page => Url.Action("AjaxSurveyGeographyList", new { page }),
                  PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "result", OnSuccess = "removeListAndPagination()" }))

            @if (!(Model.PageCount <= 0))
            {
                <p class="pagination-info">Страница @Model.PageNumber из @Model.PageCount</p>
            }
        </div>
    </div>
</div>

<!-- Bootstrap modal popup -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">Удаление</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="success-message"> Вы действительно хотите удалить запись? </p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger delete-confirm">Да</button>
                <button class="btn btn-default delete-cancel" data-dismiss="modal">Нет</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        modalRemovalWindow('/SurveyGeography/Delete');
        pagination();
    </script>
}