Questionnaire/Questionnaire.WEB/Controllers/AnswerController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Infrastructure.Exceptions;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class AnswerController : Controller
    {
        private const int _itemsPerPage = 10;
        private IAnswerService AnswerService;

        public AnswerController(IAnswerService answerService)
        {
            AnswerService = answerService;
        }

        [Authorize(Roles = "admin, manager")]
        public ActionResult AjaxAnswerList(int? page)
        {
            IEnumerable<AnswerDTO> answerDTOs = AnswerService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<AnswerVM> answerVMs = Mapper.Map<IEnumerable<AnswerVM>>(answerDTOs);

            return PartialView(answerVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Answer
        [Authorize(Roles = "admin, manager")]
        public ActionResult Index(int? page)
        {

            IEnumerable<AnswerDTO> answerDTOs = AnswerService
               .GetListOrderedByName()
               .ToList();
            IEnumerable<AnswerVM> answerVMs = Mapper.Map<IEnumerable<AnswerVM>>(answerDTOs);

            return View(answerVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Answer/Details/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Details(int? id)
        {
            try
            {
                AnswerDTO answerDTO = AnswerService.Get(id);
                AnswerVM answerVMs = Mapper.Map<AnswerVM>(answerDTO);

                return View(answerVMs);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        // GET: Answer/Create
        [Authorize(Roles = "admin, manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Answer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, manager")]
        public ActionResult Create([Bind(Include = "Name")] AnswerVM answerVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AnswerDTO answerDTO = Mapper.Map<AnswerDTO>(answerVM);
                    AnswerService.Add(answerDTO);
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new
                {
                    hasError = true,
                    data = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Answer/Edit/5
        [Authorize(Roles = "admin, manager")]
        public ActionResult Edit(int? id)
        {
            try
            {
                AnswerDTO answerDTO = AnswerService.Get(id);
                AnswerVM answerVM = Mapper.Map<AnswerVM>(answerDTO);
                return View(answerVM);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        // POST: Answer/Edit/5
        [HttpPost]
        [Authorize(Roles = "admin, manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] AnswerVM answerVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AnswerDTO answerDTO = Mapper.Map<AnswerDTO>(answerVM);
                    AnswerService.Update(answerDTO);
                    return RedirectToAction("Index");
                }
                return View(answerVM);
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new
                {
                    hasError = true,
                    data = ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Answer/Delete/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                AnswerService.Delete(id);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
            catch (HasRelationsException)
            {
                return Content("Удаление невозможно.");
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FindAnswers(string value, string type)
        {
            value = value.Trim().ToLower();

            List<AnswerDTO> answerDTOs = AnswerService
                .GetAnswersBy(type, value)
                .ToList();

            List<AnswerVM> answerVMs = Mapper.Map<IEnumerable<AnswerVM>>(answerDTOs).ToList();

            return PartialView(answerVMs);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Questionnaire/Questionnaire.WEB/Controllers/FormController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Infrastructure.Exceptions;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class FormController : Controller
    {
        private const int _itemsPerPage = 10;
        private IFormService FormService;
        private ISurveyGeographyService SurveyGeographyService;
        private IHousingTypeService HousingTypeService;
        private IDistrictService DistrictService;
        private IInterviewerService InterviewerService;

        public FormController(IFormService formService,
            ISurveyGeographyService surveyGeographyService,
            IHousingTypeService housingTypeService,
            IDistrictService districtService,
            IInterviewerService interviewerService)
        {
            FormService = formService;
            SurveyGeographyService = surveyGeographyService;
            HousingTypeService = housingTypeService;
            DistrictService = districtService;
            InterviewerService = interviewerService;
        }

        [Authorize(Roles = "admin, manager, user")]
        public ActionResult AjaxFormList(int? page)
        {
            IEnumerable<FormDTO> formDTOs = FormService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<FormVM> formVMs = Mapper.Map<IEnumerable<FormVM>>(formDTOs);

            return PartialView(formVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }
        // GET: Form
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Index(int? page)
        {
            IEnumerable<FormDTO> formDTOs = FormService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<FormVM> formVMs = Mapper.Map<IEnumerable<FormVM>>(formDTOs);

            return PartialView(formVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Form/Details/5
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Details(int? id)
        {
            try
            {
                FormDTO formDTO = FormService.Get(id);
                FormVM formVM = Mapper.Map<FormVM>(formDTO);

                return View(formVM);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Create()
        {
            ViewBag.SurveyGeographyId = GetSurveyGeographySelectList();
            ViewBag.HousingTypeId = GetHousingTypeSelectList();
            ViewBag.DistrictId = GetDistrictSelectList();
            ViewBag.InterviewerId = GetInterviewerSelectList();

            ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");
            ViewBag.Time = DateTime.Now.ToString("HH\\:mm");

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager, user")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NumberForm, SurveyGeographyId, HousingTypeId, DistrictId, InterviewerId, Address, Phone,InterviewDate, StartTime, EndTime")] FormVM formVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    FormDTO formDTO = Mapper.Map<FormDTO>(formVM);
                    FormService.Add(formDTO);
                    return RedirectToAction("Index");
                }
                ViewBag.SurveyGeographyId = GetSurveyGeographySelectList(formVM.SurveyGeographyId);
                ViewBag.HousingTypeId = GetHousingTypeSelectList(formVM.HousingTypeId);
                ViewBag.DistrictId = GetDistrictSelectList(formVM.DistrictId);
                ViewBag.InterviewerId = GetInterviewerSelectList(formVM.InterviewerId);
                ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");
                ViewBag.Time = DateTime.Now.ToString("HH\\:mm");

                return View(formVM);
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new { hasError = true, data = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Form/Edit/5
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Edit(int? id)
        {
            try
            {
                FormDTO formDTO = FormService.Get(id);
                FormVM formVM = Mapper.Map<FormVM>(formDTO);

                ViewBag.SurveyGeographyId = GetSurveyGeographySelectList(formVM.SurveyGeographyId);
                ViewBag.HousingTypeId = GetHousingTypeSelectList(formVM.HousingTypeId);
                ViewBag.DistrictId = GetDistrictSelectList(formVM.DistrictId);
                ViewBag.InterviewerId = GetInterviewerSelectList(formVM.InterviewerId);

                return View(formVM);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager, user")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, NumberForm, SurveyGeographyId, HousingTypeId, DistrictId, InterviewerId, Address, Phone,InterviewDate, StartTime, EndTime")] FormVM formVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    FormDTO formDTO = Mapper.Map<FormDTO>(formVM);
                    FormService.Update(formDTO);
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError(null, "Что-то пошло не так. Не удалось сохранить изменения.");

                ViewBag.SurveyGeographyId = GetSurveyGeographySelectList(formVM.SurveyGeographyId);
                ViewBag.HousingTypeId = GetHousingTypeSelectList(formVM.HousingTypeId);
                ViewBag.DistrictId = GetDistrictSelectList(formVM.DistrictId);
                ViewBag.InterviewerId = GetInterviewerSelectList(formVM.InterviewerId);

                return View(formVM);
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new {hasError = true, data = ex.Message }, JsonRequestBehavior.AllowGet);
            }
    
        }

        public SelectList GetSurveyGeographySelectList(short? selectedValue = null)
        {
            return new SelectList(SurveyGeographyService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        public SelectList GetHousingTypeSelectList(short? selectedValue = null)
        {
            return new SelectList(HousingTypeService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        public SelectList GetDistrictSelectList(short? selectedValue = null)
        {
            return new SelectList(DistrictService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        public SelectList GetInterviewerSelectList(short? selectedValue = null)
        {
            return new SelectList(InterviewerService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        // GET: Form/Delete/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                FormService.Delete(id);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
            catch (HasRelationsException)
            {
                return Content("Удаление невозможно.");
            }
            return RedirectToAction("Index");
        }

        public ActionResult RemoveData(int id)
        {
            try
            {
                FormService.RemoveData(id);
                TempData["success"] = "Данные анкеты удалены.";
            }
            catch (Exception)
            {
                return Content("Произошла ошибка.");
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Questionnaire/Questionnaire.WEB/Controllers/UserController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Account;
using Questionnaire.WEB.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class UserController : Controller
    {
        private const int ItemsPerPage = 10;

        private readonly IUserService UserService;
        private readonly IAccountService AccountService;

        public UserController(IUserService userService, IAccountService accountService)
        {
            UserService = userService;
            AccountService = accountService;
        }

        [Authorize(Roles = "admin")]
        public ActionResult Index(int? page)
        {
            var userDTOs = UserService.GetAllUsers().ToList();
            var userVMs = Mapper.Map<IEnumerable<UserVM>>(userDTOs).ToPagedList(page ?? 1, ItemsPerPage);

            return View(userVMs);
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> ChangeRole(string userId)
        {
            if (userId == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var role = await UserService.GetUserRole(userId);
            ChangeRoleModel model = new ChangeRoleModel
            {
                UserId = userId,
                OldRole = role,
                Role = role
            };

            ViewBag.Role = GetRoleNameSelectList(model.Role);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangeRole([Bind(Include = "UserId,OldRole,Role")] ChangeRoleModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ChangeRoleDTO changeRoleDTO = new ChangeRoleDTO
                    {
                        UserId = model.UserId,
                        OldRole = model.OldRole,
                        Role = model.Role
                    };
                    await UserService.ChangeUserRole(changeRoleDTO);
                    TempData["success"] = "Изменения сохранены.";
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Произошла ошибка. Попробуйте еще раз либо обратитесь к администратору.");
                }
            }
            ViewBag.Role = GetRoleNameSelectList(model.Role);

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id)
        {
            try
            {
                await UserService.DeleteUser(id);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (Exception)
            {
                TempData["fail"] = "Произошла ошибка.";
            }

            return RedirectToAction("Index");
        }

        private SelectList GetRoleNameSelectList(string selectedValue = null)
        {
            return new SelectList(AccountService.GetAllRoles().ToList(), "Name", "Description", selectedValue);
        }
    }
}

Questionnaire/Questionnaire.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Вопросник</title>
    <link href="~/Content/Chosen/chosen.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/jquery.mCustomScrollbar.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h4 class="text-center"><a href="@Url.Action("Index", "Home")">Вопросник</a></h4>
            </div>

            <ul class="list-unstyled components">
                <!-- <p>Навигация</p> -->
                <li id="main-page-menu-item" class="active">
                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-home" aria-hidden="true"></i> Главная</a>
                </li>
                @if (User.IsInRole("admin"))
                {
                    <li id="user-page-menu-item">
                        <a href="@Url.Action("Index", "User")"><i class="fa fa-users" aria-hidden="true"></i> Пользователи</a>
                    </li>
                    <li id="question-answer-page-menu-item">
                        <!-- class="active" -->
                        <a href="#questionAnswerDropdown" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-comment" aria-hidden="true"></i> Вопросы / Ответы</a>
                        <ul class="collapse list-unstyled" id="questionAnswerDropdown">
                            <li>
                                <a href="@Url.Action("Index", "QuestionType")">Типы вопросов</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Question")">Вопросы</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Answer")">Ответы</a>
                            </li>
                        </ul>
                    </li>
                    <li id="survey-geography-page-menu-item">
                        <!-- class="active" -->
                        <a href="#surveyGeographyDropdown" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-globe" aria-hidden="true"></i> География обследования</a>
                        <ul class="collapse list-unstyled" id="surveyGeographyDropdown">
                            <li>
                                <a href="@Url.Action("Index", "SurveyGeography")">Место обследования</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "HousingType")">Типы жилья</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "District")">Районы</a>
                            </li>
                        </ul>
                    </li>
                    <li id="contacts-page-menu-item">
                        <!-- class="active" -->
                        <a href="#contactDropdown" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-address-card" aria-hidden="true"></i> Контакты / Анкеты</a>
                        <ul class="collapse list-unstyled" id="contactDropdown">
                            <li>
                                <a href="@Url.Action("Index", "Form")">Анкеты</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Family")">Респонденты</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Interviewer")">Интервьюеры</a>
                            </li>
                        </ul>
                    </li>

                    @*<li id="questionary-page-menu-item">
                <a href="@Url.Action("Index", "Form")"><i class="fa fa-wpforms" aria-hidden="true"></i> Анкеты</a>
            </li>*@
                }
                else if (User.IsInRole("manager"))
                {
                    <li id="question-answer-page-menu-item">
                        <!-- class="active" -->
                        <a href="#questionAnswerDropdown" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-comment" aria-hidden="true"></i> Вопросы / Ответы</a>
                        <ul class="collapse list-unstyled" id="questionAnswerDropdown">
                            <li>
                                <a href="@Url.Action("Index", "QuestionType")">Типы вопросов</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Question")">Вопросы</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Answer")">Ответы</a>
                            </li>
                        </ul>
                    </li>
                    <li id="survey-geography-page-menu-item">
                        <!-- class="active" -->
                        <a href="#surveyGeographyDropdown" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-globe" aria-hidden="true"></i> География обследования</a>
                        <ul class="collapse list-unstyled" id="surveyGeographyDropdown">
                            <li>
                                <a href="@Url.Action("Index", "SurveyGeography")">Место обследования</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "HousingType")">Типы жилья</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "District")">Районы</a>
                            </li>
                        </ul>
                    </li>
                    <li id="contacts-page-menu-item">
                        <!-- class="active" -->
                        <a href="#contactDropdown" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-address-card" aria-hidden="true"></i> Контакты / Анкеты</a>
                        <ul class="collapse list-unstyled" id="contactDropdown">
                            <li>
                                <a href="@Url.Action("Index", "Interviewer")">Интервьюеры</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Form")">Анкеты</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Family")">Респонденты</a>
                            </li>
                        </ul>
                    </li>
                }
                else if (User.IsInRole("user"))
                {
                    <li id="contacts-page-menu-item">
                        <!-- class="active" -->
                        <a href="#contactDropdown" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-address-card" aria-hidden="true"></i> Контакты / Анкеты</a>
                        <ul class="collapse list-unstyled" id="contactDropdown">
                            <li>
                                <a href="@Url.Action("Index", "Form")">Анкеты</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Family")">Респонденты</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Interviewer")">Интервьюеры</a>
                            </li>
                        </ul>
                    </li>
                }
            </ul>
            <ul class="list-unstyled account">
                @if (!User.Identity.IsAuthenticated)
                {
                    <li id="login-page-menu-item">
                        <a href="@Url.Action("Login", "Account")"><i class="fa fa-sign-in icon-muted" aria-hidden="true"></i> Войти</a>
                    </li>
                }
                else
                {
                    <li id="change-email-page-menu-item">
                        <a href="@Url.Action("ChangeEmail", "Account")"><i class="fa fa-at icon-muted" aria-hidden="true"></i> Сменить почту</a>
                    </li>
                    <li id="change-password-page-menu-item">
                        <a href="@Url.Action("ChangePassword", "Account")"><i class="fa fa-unlock-alt icon-muted" aria-hidden="true"></i> Сменить пароль</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Logout", "Account")"><i class="fa fa-sign-out icon-muted" aria-hidden="true"></i> Выйти</a>
                    </li>
                }
            </ul>
        </nav>

        <!-- top nav -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-light">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                    <span>Меню</span>
                </button>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="justify-content-end text-muted logged-as">
                        Вы вошли как: @User.Identity.Name
                    </div>
                }

            </div>
        </nav>

        <!-- Page Content  -->
        <div id="content">
            <div id="form-saved-success" class="p-3 mb-2 bg-success text-white d-none">
                <div class="container">
                    <b>Данные сохранены.</b>
                    <span class="float-right message-div-close" onclick="closeSuccessFormSaveMessage()"><i class="fa fa-times" aria-hidden="true"></i></span>
                </div>
            </div>
            <div id="form-saved-failed" class="p-3 mb-2 bg-danger text-white d-none">
                <div class="container">
                    <b>Не удалось сохранить данные.</b>
                    <span class="float-right message-div-close" onclick="closeFailedFormSaveMessage()"><i class="fa fa-times" aria-hidden="true"></i></span>
                </div>
            </div>
            @if (TempData["success"] != null)
            {
                <div id="message-div" class="p-3 mb-2 bg-success text-white">
                    <div class="container">
                        <b>@TempData["success"]</b>
                        <span class="float-right message-div-close" onclick="closeMessageDiv()"><i class="fa fa-times" aria-hidden="true"></i></span>
                    </div>
                </div>
            }
            @if (TempData["fail"] != null)
            {
                <div id="message-div" class="p-3 mb-2 bg-danger text-white">
                    <div class="container">
                        <b>@TempData["fail"]</b>
                        <span class="float-right message-div-close" onclick="closeMessageDiv()"><i class="fa fa-times" aria-hidden="true"></i></span>
                    </div>
                </div>
            }


            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js")
    <script src="~/Scripts/jquery.mCustomScrollbar.concat.min.js"></script>

    <script src="~/Scripts/app.js"></script>
    <script src="~/Scripts/chosen.jquery.min.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
    <script src="~/Scripts/pagination.js"></script>

    <script>
        menuInit();
        activeMenuItem();
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>