Questionnaire/Questionnaire.WEB/Controllers/FamilyController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Infrastructure.Exceptions;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class FamilyController : Controller
    {
        private const int _itemsPerPage = 10;
        private IFamilyService FamilyService;
        private IFormService FormService;

        public FamilyController(IFamilyService familyService, IFormService formService)
        {
            FamilyService = familyService;
            FormService = formService;
        }

        [Authorize(Roles = "admin, manager, user")]
        public ActionResult AjaxFamilyList(int? page)
        {
            IEnumerable<FamilyDTO> familyDTOs = FamilyService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<FamilyVM> familyVMs = Mapper.Map<IEnumerable<FamilyVM>>(familyDTOs);

            return PartialView(familyVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }
        // GET: Family
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Index(int? page)
        {
            IEnumerable<FamilyDTO> familyDTOs = FamilyService
                 .GetListOrderedByName()
                 .ToList();
            IEnumerable<FamilyVM> familyVMs = Mapper.Map<IEnumerable<FamilyVM>>(familyDTOs);

            return PartialView(familyVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Family/Details/5
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Details(int? id)
        {
            try
            {
                FamilyDTO familyDTO = FamilyService.Get(id);
                FamilyVM familyVM = Mapper.Map<FamilyVM>(familyDTO);

                return View(familyVM);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Create()
        {
            ViewBag.FormId = GetFormIdSelectList();

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager, user")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Age, Sex, FormId")] FamilyVM familyVM)
        {
            if (ModelState.IsValid)
            {
                FamilyDTO familyDTO = Mapper.Map<FamilyDTO>(familyVM);
                //int questionId = QuestionService.AddAndGetId(questionDTO);
                FamilyService.Add(familyDTO);
                return RedirectToAction("Index");
            }
            ViewBag.FormId = GetFormIdSelectList(familyVM.FormId);

            return View(familyVM);
        }

        // GET: Family/Edit/5
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Edit(int? id)
        {
            try
            {
                FamilyDTO familyDTO = FamilyService.Get(id);
                FamilyVM familyVM = Mapper.Map<FamilyVM>(familyDTO);

                ViewBag.FormId = GetFormIdSelectList(familyVM.FormId);

                return View(familyVM);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager, user")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Age, Sex, FormId")] FamilyVM familyVM)
        {
            if (ModelState.IsValid)
            {
                FamilyDTO familyDTO = Mapper.Map<FamilyDTO>(familyVM);
                FamilyService.Update(familyDTO);
                return RedirectToAction("Index");
            }
            //else
            //    ModelState.AddModelError(null, "Что-то пошло не так. Не удалось сохранить изменения.");

            ViewBag.FormId = GetFormIdSelectList(familyVM.FormId);

            return View(familyVM);
        }

        [Authorize(Roles = "admin, manager, user")]
        public SelectList GetFormIdSelectList(int? selectedValue = null)
        {
            return new SelectList(FormService.GetAll().ToList(), "Id", "NumberForm", selectedValue);
        }

        // GET: Family/Delete/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                FamilyService.Delete(id);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
            catch (HasRelationsException)
            {
                return Content("Удаление невозможно.");
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Questionnaire/Questionnaire.WEB/Controllers/FormController.cs
using AutoMapper;
using PagedList;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Infrastructure.Exceptions;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class FormController : Controller
    {
        private const int _itemsPerPage = 10;
        private IFormService FormService;
        private ISurveyGeographyService SurveyGeographyService;
        private IHousingTypeService HousingTypeService;
        private IDistrictService DistrictService;
        private IInterviewerService InterviewerService;

        public FormController(IFormService formService,
            ISurveyGeographyService surveyGeographyService,
            IHousingTypeService housingTypeService,
            IDistrictService districtService,
            IInterviewerService interviewerService)
        {
            FormService = formService;
            SurveyGeographyService = surveyGeographyService;
            HousingTypeService = housingTypeService;
            DistrictService = districtService;
            InterviewerService = interviewerService;
        }

        [Authorize(Roles = "admin, manager, user")]
        public ActionResult AjaxFormList(int? page)
        {
            IEnumerable<FormDTO> formDTOs = FormService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<FormVM> formVMs = Mapper.Map<IEnumerable<FormVM>>(formDTOs);

            return PartialView(formVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }
        // GET: Form
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Index(int? page)
        {
            IEnumerable<FormDTO> formDTOs = FormService
                .GetListOrderedByName()
                .ToList();
            IEnumerable<FormVM> formVMs = Mapper.Map<IEnumerable<FormVM>>(formDTOs);

            return PartialView(formVMs.ToPagedList(page ?? 1, _itemsPerPage));
        }

        // GET: Form/Details/5
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Details(int? id)
        {
            try
            {
                FormDTO formDTO = FormService.Get(id);
                FormVM formVM = Mapper.Map<FormVM>(formDTO);

                return View(formVM);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Create()
        {
            ViewBag.SurveyGeographyId = GetSurveyGeographySelectList();
            ViewBag.HousingTypeId = GetHousingTypeSelectList();
            ViewBag.DistrictId = GetDistrictSelectList();
            ViewBag.InterviewerId = GetInterviewerSelectList();

            ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");
            ViewBag.Time = DateTime.Now.ToString("HH\\:mm");

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager, user")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NumberForm, SurveyGeographyId, HousingTypeId, DistrictId, InterviewerId, Address, Phone,InterviewDate, StartTime, EndTime")] FormVM formVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    FormDTO formDTO = Mapper.Map<FormDTO>(formVM);
                    FormService.Add(formDTO);
                    return RedirectToAction("Index");
                }
                ViewBag.SurveyGeographyId = GetSurveyGeographySelectList(formVM.SurveyGeographyId);
                ViewBag.HousingTypeId = GetHousingTypeSelectList(formVM.HousingTypeId);
                ViewBag.DistrictId = GetDistrictSelectList(formVM.DistrictId);
                ViewBag.InterviewerId = GetInterviewerSelectList(formVM.InterviewerId);
                ViewBag.Today = DateTime.Now.ToString("yyyy-MM-dd");
                ViewBag.Time = DateTime.Now.ToString("HH\\:mm");

                return View(formVM);
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new { hasError = true, data = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Form/Edit/5
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Edit(int? id)
        {
            try
            {
                FormDTO formDTO = FormService.Get(id);
                FormVM formVM = Mapper.Map<FormVM>(formDTO);

                ViewBag.SurveyGeographyId = GetSurveyGeographySelectList(formVM.SurveyGeographyId);
                ViewBag.HousingTypeId = GetHousingTypeSelectList(formVM.HousingTypeId);
                ViewBag.DistrictId = GetDistrictSelectList(formVM.DistrictId);
                ViewBag.InterviewerId = GetInterviewerSelectList(formVM.InterviewerId);

                return View(formVM);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            catch (NotFoundException)
            {
                return HttpNotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, manager, user")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, NumberForm, SurveyGeographyId, HousingTypeId, DistrictId, InterviewerId, Address, Phone,InterviewDate, StartTime, EndTime")] FormVM formVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    FormDTO formDTO = Mapper.Map<FormDTO>(formVM);
                    FormService.Update(formDTO);
                    return RedirectToAction("Index");
                }
                else
                    ModelState.AddModelError(null, "Что-то пошло не так. Не удалось сохранить изменения.");

                ViewBag.SurveyGeographyId = GetSurveyGeographySelectList(formVM.SurveyGeographyId);
                ViewBag.HousingTypeId = GetHousingTypeSelectList(formVM.HousingTypeId);
                ViewBag.DistrictId = GetDistrictSelectList(formVM.DistrictId);
                ViewBag.InterviewerId = GetInterviewerSelectList(formVM.InterviewerId);

                return View(formVM);
            }
            catch (UniqueConstraintException ex)
            {
                return Json(new {hasError = true, data = ex.Message }, JsonRequestBehavior.AllowGet);
            }
    
        }

        public SelectList GetSurveyGeographySelectList(short? selectedValue = null)
        {
            return new SelectList(SurveyGeographyService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        public SelectList GetHousingTypeSelectList(short? selectedValue = null)
        {
            return new SelectList(HousingTypeService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        public SelectList GetDistrictSelectList(short? selectedValue = null)
        {
            return new SelectList(DistrictService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        public SelectList GetInterviewerSelectList(short? selectedValue = null)
        {
            return new SelectList(InterviewerService.GetAll().ToList(), "Id", "Name", selectedValue);
        }

        // GET: Form/Delete/5
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                FormService.Delete(id);
            }
            catch (NotFoundException)
            {
                return HttpNotFound();
            }
            catch (HasRelationsException)
            {
                return Content("Удаление невозможно.");
            }
            return RedirectToAction("Index");
        }

        public ActionResult RemoveData(int id)
        {
            try
            {
                FormService.RemoveData(id);
                TempData["success"] = "Данные анкеты удалены.";
            }
            catch (Exception)
            {
                return Content("Произошла ошибка.");
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Questionnaire/Questionnaire.WEB/Controllers/FormDataController.cs
using AutoMapper;
using Questionnaire.BLL.DTO;
using Questionnaire.BLL.Interfaces;
using Questionnaire.WEB.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class FormDataController : Controller
    {
        private IQuestionAnswerService QuestionAnswerService;
        private IQuestionTypeService QuestionTypeService;
        private IDataService DataService;
        private IFormService FormService;

        public FormDataController(IQuestionAnswerService questionAnswerService, IQuestionTypeService questionTypeService, IDataService dataService, IFormService formService)
        {
            QuestionAnswerService = questionAnswerService;
            QuestionTypeService = questionTypeService;
            DataService = dataService;
            FormService = formService;
        }

        // GET: FormDataControlelr
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult QuestionAnswers(int id, int questionTypeId)
        {
            try
            {
                ViewBag.FormId = id; 
                ViewBag.Sections = Mapper.Map<IEnumerable<QuestionTypeVM>>(QuestionTypeService.GetAll().ToList());
                ViewBag.Section = QuestionTypeService.Get(questionTypeId).Name;
                var formDataDTOs = QuestionAnswerService.GetQuestionAnswersByQuestionType(questionTypeId).ToList();
                var formDataVMs = Mapper.Map<IEnumerable<FormDataVM>>(formDataDTOs);
                //IEnumerable<AnswerVM> answerVMs = Mapper.Map<IEnumerable<AnswerVM>>(answerDTOs);

                return View(formDataVMs);
            }
            catch (ArgumentNullException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public bool SaveForm(int formId, int[] questionIds, DataDTO[] answers, bool editCheckBox)
        {
            DataService.UpdateAnswers(formId, questionIds, answers, editCheckBox);

            return true;
        }
    }
}

Questionnaire/Questionnaire.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Questionnaire.WEB.Controllers
{
    public class HomeController : Controller
    {
        [Authorize(Roles = "admin, manager, user")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Questionnaire/Questionnaire.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Questionnaire/Questionnaire.WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Questionnaire/Questionnaire.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@

<div class="jumbotron">
    <h1 style="text-align:center">
        АНКЕТА
    </h1>
    <h1 style="text-align:center">
        ВИКТИМОЛОГИЧЕСКОГО ИССЛЕДОВАНИЯ В г. БИШКЕК И НОВОСТРОЙКАХ
    </h1>
    <h5>
        Здравствуйте! Я работаю в Национальном статистическом комитете Кыргызской Республики. Мы проводим обследование домашних хозяйств, чтобы определить отношение населения к проблемам безопасности
        и преступности, а также их влияние на жизнь людей в г.Бишкек и новостройках. Обследование будет способствовать разработке мер по предупреждению преступности и позволит лучше понять значение
        вопросов безопасности в жизни общества.
        У нас есть письмо Председателя Нацстаткома о проведении этой работы (ПЕРЕДАЙТЕ ПИСЬМО). Длительность интервью составит примерно 15-25 минут. Ваше участие в исследовании добровольное и не
        предполагает оплату или подарки, но Ваше мнение является для нас очень важным. Вся информация, которую Вы дадите при ответах на вопросы, строго конфиденциальна (секретная) и будет использоваться
        только в обобщенном виде для анализа, без указания Вашего имени. Если у Вас возникнут какие-либо вопросы или замечания, Вы можете сообщить их мне или позвонить по телефону: (0312) 66 40 42.
    </h5>
</div>
<hr/>
<div class="container marketing">
    <div class="row">
        @if (User.IsInRole("admin") || User.IsInRole("manager"))
        {
            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Вопросы</h2>
                <p>В разделе вопросы вы можете добавлять, редактировать или удалять вопросы. А также добавлять все возможные варианты ответов к вопросам. </p>
                <p><a class="btn btn-secondary" href="@Url.Action("Index", "Question")" role="button">Перейти »</a></p>
            </div>
            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Анкеты</h2>
                <p>В разделе анкеты вы можете добавлять, редактировать или удалять анкеты.</p>
                <p><a class="btn btn-secondary" href="@Url.Action("Index", "Form")" role="button">Перейти »</a></p>
            </div>
            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Форма</h2>
                <p>В разделе форм вы можете заполнить анкету отвечая на вопросы.</p>
                <p><a class="btn btn-secondary" href="@Url.Action("QuestionAnswers", "FormData", new { questionTypeId = 1 })" role="button">Перейти »</a></p>
            </div>
        }
        else
        {
            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Анкеты</h2>
                <p>В разделе анкеты вы можете добавлять, редактировать и переходить к заполнению анкеты.</p>
                <p><a class="btn btn-secondary" href="@Url.Action("Index", "Form")" role="button">Перейти »</a></p>
            </div>
            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Респонденты</h2>
                <p>В разделе этом вы можете добавлять, редактировать информацию о респондентах.</p>
                <p><a class="btn btn-secondary" href="@Url.Action("Index", "Family")" role="button">Перейти »</a></p>
            </div>
            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Интервьюеры</h2>
                <p>В разделе этом вы можете добавлять, редактировать информацию о интервьюерах.</p>
                <p><a class="btn btn-secondary" href="@Url.Action("Index", "Interviewer", new { questionTypeId = 1 })" role="button">Перейти »</a></p>
            </div>
        }
    </div>
</div>